import type { Rule, Shortcut } from '@unocss/core'

import type { FullTheme } from '../theme'
import { container, containerShortcuts } from './container'
import { inset } from './inset'
import {
  aspectRatio,
  boxDecorationBreak,
  boxSizing,
  breakAfter,
  breakBefore,
  breakInside,
  clear,
  columns,
  display,
  flex,
  flexBasic,
  flexDirection,
  flexGrow,
  flexShrink,
  flexWrap,
  floats,
  gridAutoColumns,
  gridAutoFlow,
  gridAutoRows,
  gridColumn,
  gridRow,
  gridTemplateColumns,
  gridTemplateRows,
  isolation,
  objectFit,
  objectPosition,
  order,
  overflow,
  overscrollBehavior,
  position,
  visibility,
  zIndex,
} from './simples'

export const rules: Rule<FullTheme>[] = [
  // Layout
  ...aspectRatio,
  container,
  ...columns,
  ...breakAfter,
  ...breakBefore,
  ...breakInside,
  ...boxDecorationBreak,
  ...boxSizing,
  ...display,
  ...floats,
  ...clear,
  ...isolation,
  ...objectFit,
  ...objectPosition,
  ...overflow,
  ...overscrollBehavior,
  ...position,
  ...inset,
  ...visibility,
  ...zIndex,
  // Flexbox & Grid
  ...flexBasic,
  ...flexDirection,
  ...flexWrap,
  ...flex,
  ...flexGrow,
  ...flexShrink,
  ...order,
  ...gridTemplateColumns,
  ...gridColumn,
  ...gridTemplateRows,
  ...gridRow,
  ...gridAutoFlow,
  ...gridAutoColumns,
  ...gridAutoRows,
]

export const shortcuts: Shortcut<FullTheme>[] = [containerShortcuts]
